## Fixes:
- sort in absolute value
- Put it in a module / pip / conda
- Add differential expression feature
- Calculate everything in matrices rather than for loops
- Pearson R vs. Spearman R?


- Required input values: Pandas vs. numpy

- There is a bug if you select 0 cells --> endlessly loops through showUMAPScatter with self.requestSelection == True



## Installation:
Currently:
conda env create -n py5coding -f http://py5.ixora.io/install/py5_environment.yml
conda install scipy
python setup.py install ## within embedview directory 

In [1]:
import pandas as pd
import numpy as np
from scipy.io import mmread
import time
import scipy.sparse as sparse

In [2]:
%load_ext py5
%gui osx
%load_ext autoreload
%autoreload 2

In [3]:
print("LOADING UMAP DATA...")

_umap = pd.read_csv('../data/Tcell50K_expression_log2TP10K_20210409.umap.tsv', sep='\t', index_col=0)
_umap.head()

LOADING UMAP DATA...


UMAP_1     UMAP_2
AAACATACACCCAA-1   3.975246  10.370767
AAACATACCCCTCA-1   9.388674   1.431675
AAACATACCGGAGA-1  12.206055  11.943375
AAACATACTCTTCA-1  15.312049  -2.373958
AAACATACTGGATC-1  10.571509  -6.149192

In [4]:
print("LOADING GENE EXPRESSION DATA...")

_expr_sparse = mmread('../data/Tcell50K_expression_log2TP10K_20210409.mtx')
_expr_sparse

LOADING GENE EXPRESSION DATA...


<52899x12563 sparse matrix of type '<class 'numpy.float64'>'
	with 28209469 stored elements in COOrdinate format>

In [5]:
genes = pd.read_csv('../data/Tcell50K_expression_log2TP10K_20210409.genes.tsv', sep='\t', header=None)
barcodes = pd.read_csv('../data/Tcell50K_expression_log2TP10K_20210409.barcodes.tsv', sep='\t', header=None)

In [6]:
_expr = pd.DataFrame(_expr_sparse.todense(), columns=genes[0], index=barcodes[0])

In [7]:
_expr.head()

0                 LINC00115  FAM41C  NOC2L  KLHL17  PLEKHN1  HES4  ISG15  \
0                                                                          
AAACATACACCCAA-1        0.0     0.0    0.0     0.0      0.0   0.0    0.0   
AAACATACCCCTCA-1        0.0     0.0    0.0     0.0      0.0   0.0    0.0   
AAACATACCGGAGA-1        0.0     0.0    0.0     0.0      0.0   0.0    0.0   
AAACATACTCTTCA-1        0.0     0.0    0.0     0.0      0.0   0.0    0.0   
AAACATACTGGATC-1        0.0     0.0    0.0     0.0      0.0   0.0    0.0   

0                 AGRN  C1orf159  TTLL10  ...  MT-ATP6  MT-CO3  MT-ND3  \
0                                         ...                            
AAACATACACCCAA-1   0.0       0.0     0.0  ...   0.0000  3.5257  2.2240   
AAACATACCCCTCA-1   0.0       0.0     0.0  ...   2.1965  4.0423  0.0000   
AAACATACCGGAGA-1   0.0       0.0     0.0  ...   0.0000  2.7820  0.0000   
AAACATACTCTTCA-1   0.0       0.0     0.0  ...   0.0000  2.2008  2.2008   
AAACATACTGGATC-1   0.0       0.0     0.0  ...   2.7849  2.7849  0.0000   

0                 MT-ND4L  MT-ND4  MT-ND5  MT-ND6  MT-CYB  PNRC2-1  SRSF10-1  
0                                                                             
AAACATACACCCAA-1      0.0  2.8615  2.2240     0.0  3.2477    2.224       0.0  
AAACATACCCCTCA-1      0.0  2.8325  2.1965     0.0  3.2181    0.000       0.0  
AAACATACCGGAGA-1      0.0  2.7820  3.1666     0.0  3.1666    0.000       0.0  
AAACATACTCTTCA-1      0.0  2.8370  0.0000     0.0  3.2227    0.000       0.0  
AAACATACTGGATC-1      0.0  3.1695  2.1516     0.0  2.1516    0.000       0.0  

[5 rows x 12563 columns]

In [9]:
_expr_sparse_csc= sparse.csc_matrix(_expr_sparse)

In [10]:
#from umap_explorer import UMAPexplorer
import sys
sys.path.append('../umap_explorer/')
from umap_explorer import UMAPexplorer

test = UMAPexplorer(_umap, _expr)
test.explore_data()

0.653817892074585 seconds to select and project cells
Selected 352 cells
Calculating correlations...


../umap_explorer/umap_explorer.py:499: RuntimeWarning: invalid value encountered in true_divide
  rs = np.dot(DP, DO) / np.sqrt(np.sum(DO ** 2, 0) * np.sum(DP ** 2))


0.7709219455718994 seconds to calculate correlations. Sparsity:  False
1.0532300472259521 seconds to select and project cells
Selected 5388 cells
Calculating correlations...
7.078086853027344 seconds to calculate correlations. Sparsity:  False
Selected mode 2
0.4046480655670166 seconds to select and project cells
Selected 327 cells
Calculating differential expression...
7.341778993606567 seconds to calculate genesums. Sparsity:  False
21.91492199897766 seconds to calculate squared genesums. Sparsity:  False
29.397571086883545 seconds to calculate differential expression. Sparsity:  False
1.079200029373169 seconds to select and project cells
Selected 5417 cells
Calculating differential expression...
3.2213268280029297 seconds to calculate differential expression. Sparsity:  False
EXPORTING DATA...
BYE


In [11]:

#from umap_explorer import UMAPexplorer
import sys
sys.path.append('../umap_explorer/')
from umap_explorer import UMAPexplorer

test_csc = UMAPexplorer(_umap, _expr_sparse_csc, gene_names=list(_expr.columns))
test_csc.explore_data()

0.4065132141113281 seconds to select and project cells
Selected 396 cells
Calculating correlations...
1.6821730136871338 seconds to calculate correlations. Sparsity:  True
1.0395939350128174 seconds to select and project cells
Selected 5386 cells
Calculating correlations...
0.3787550926208496 seconds to calculate correlations. Sparsity:  True
Selected mode 2
0.5718369483947754 seconds to select and project cells
Selected 352 cells
Calculating differential expression...
0.02233600616455078 seconds to calculate genesums. Sparsity:  True
0.5646300315856934 seconds to calculate squared genesums. Sparsity:  True
0.9102721214294434 seconds to calculate differential expression. Sparsity:  True
1.1771621704101562 seconds to select and project cells
Selected 5511 cells
Calculating differential expression...
0.45987510681152344 seconds to calculate differential expression. Sparsity:  True
EXPORTING DATA...
BYE


In [14]:
start = time.time()
z =test.calculateGeneCorrelations(test.renderer.indices)
stop = time.time()
print(stop-start)
[(x.name,x.r, x.p) for x in z[:10]]

Selected 5417 cells
Calculating correlations...


../umap_explorer/umap_explorer.py:501: RuntimeWarning: invalid value encountered in true_divide
  rs = np.dot(DP, DO) / np.sqrt(np.sum(DO ** 2, 0) * np.sum(DP ** 2))


7.411128044128418


[('GZMB', -0.32614949650363956, 1.8880639679280342e-134),
 ('LGALS1', -0.30899009118183757, 3.575087769004151e-120),
 ('IFITM2', -0.3003704186066798, 2.3650231020362216e-113),
 ('S100A4', -0.2690350367863648, 1.815662224562564e-90),
 ('ACTB', -0.2646374773239628, 1.7269390898892205e-87),
 ('PFN1', -0.25680451057771914, 2.531161022516179e-82),
 ('GNLY', -0.25290176188556096, 8.156254756160819e-80),
 ('GZMH', -0.25059266003907826, 2.3715143374972015e-78),
 ('NKG7', -0.23397949182279504, 2.8953231163685266e-68),
 ('CYBA', -0.22061098395621265, 1.0534763647712336e-60)]

In [19]:
vproj = []
ind = test.renderer.indices
for i in ind:
    vproj.append(test.cells[i].proj)
vproj = np.array(vproj)

from scipy.stats import pearsonr
pearsonr(_expr['GZMB'].iloc[ind], vproj)

(-0.326149496503638, 1.8880639679313648e-134)

In [20]:
pearsonr(_expr['CYBA'].iloc[ind], vproj)

(-0.22061098395621187, 1.0534763647710057e-60)

In [52]:
start = time.time()
z2 =test_csc.calculateGeneCorrelations(test.renderer.indices)
stop = time.time()
print(stop-start)

Selected 381 cells
Calculating correlations...
0.7770411968231201


In [53]:
[(x.name,x.r) for x in z2[:10]]

[('RPL10', -0.35307996365881406),
 ('MALAT1', -0.3394227080084552),
 ('RPL13', -0.28944165407252226),
 ('RPS27', -0.27736833875230377),
 ('RPL21', -0.2703558952388874),
 ('RPL13A', -0.2633588718508012),
 ('DUSP1', -0.2587483077704914),
 ('JUNB', -0.25610997911907396),
 ('RPS6', -0.24284579955105534),
 ('RPL19', -0.23916837612053848)]

In [54]:
test.sparse

False

In [27]:
start = time.time()
z2 =test_csc.calculateGeneCorrelations_sparse2(test_csc.renderer.indices)
stop = time.time()
print(stop-start)

Selected 358 cells
Calculating correlations...


/Users/dylankotliar/miniconda3/envs/py5coding/lib/python3.8/site-packages/scipy/stats/stats.py:3913: PearsonRConstantInputWarning: An input array is constant; the correlation coefficent is not defined.
  warnings.warn(PearsonRConstantInputWarning())


5.2252960205078125


In [28]:
[x.r for x in z1[:10]]

[-0.34916670926297905,
 -0.3243703083851144,
 -0.26787387818561215,
 -0.2515203152390925,
 -0.25118051443680894,
 -0.23623141563559003,
 -0.23395850251449749,
 -0.2294874950147458,
 -0.22708333139753697,
 -0.22281041213932282]

In [29]:
[x.r for x in z2[:10]]

[-0.34916670926296794,
 -0.32437030838511416,
 -0.2678738781856031,
 -0.25152031523909263,
 -0.2511805144368089,
 -0.23623141563558459,
 -0.23395850251449749,
 -0.22948749501474663,
 -0.22708333139753706,
 -0.22281041213932104]

In [20]:
_expr_sparse_csr= sparse.csr_matrix(_expr_sparse)

In [17]:
start = time.time()
_expr_sparse.sum(axis=0)
stop =time.time()
print(stop - start)

1.2172541618347168


In [19]:
start = time.time()
_expr_sparse_csc.sum(axis=0)
stop =time.time()
print(stop - start)

1.396860122680664


In [21]:
start = time.time()
_expr_sparse_csr.sum(axis=0)
stop =time.time()
print(stop - start)

0.4743938446044922


In [18]:
start = time.time()
_expr.sum(axis=0)
stop =time.time()
print(stop - start)

55.099639892578125


In [23]:
(_expr_sparse_csc.A**2).sum(axis=0)

array([1.36004900e+03, 8.92537452e+01, 1.34238700e+04, ...,
       4.34642691e+05, 6.58844935e+03, 6.05222260e+03])

In [28]:
np.array([1,3,5]) is None

False

In [25]:
_expr.A

AttributeError: 'DataFrame' object has no attribute 'A'

In [24]:
(_expr**2).sum(axis=0)

0
LINC00115      1360.048998
FAM41C           89.253745
NOC2L         13423.870047
KLHL17          316.153331
PLEKHN1         200.692888
                 ...      
MT-ND5       119970.220405
MT-ND6         3985.982488
MT-CYB       434642.691190
PNRC2-1        6588.449353
SRSF10-1       6052.222600
Length: 12563, dtype: float64

In [47]:
from scipy.stats import pearsonr
import scipy as scipy
import time
#https://www.javaer101.com/en/article/18344934.html

In [ ]:
_expr_sparse_csr= sparse.csr_matrix(_expr_sparse)
_expr_sparse_csc= sparse.csc_matrix(_expr_sparse)

In [50]:
type(_expr_sparse_csc) in [scipy.sparse.csc.csc_matrix, np.ndarray]

True

In [32]:
x = _expr_sparse_csc
y = np.array(_expr_sparse_csc[:,100].todense()).reshape(-1)
y

array([0., 0., 0., ..., 0., 0., 0.])

In [34]:
nrow = x.shape[0]

In [35]:
yy = y - y.mean()
xm = x.mean(axis=0).A.ravel()
ys = yy / np.sqrt(np.dot(yy, yy))
xs = np.sqrt(np.add.reduceat(x.data**2, x.indptr[:-1]) - nrow*xm*xm)

correl2 = np.add.reduceat(x.data * ys[x.indices], x.indptr[:-1]) / xs

In [41]:
correl2

array([-0.00485106, -0.00130036,  0.00920662, ..., -0.00600907,
       -0.00316376,  0.00169666])

In [42]:
np.corrcoef(_expr.values[:,0], y)

array([[ 1.        , -0.00485106],
       [-0.00485106,  1.        ]])

In [43]:
np.corrcoef(_expr.values[:,-1], y)

array([[1.        , 0.00169666],
       [0.00169666, 1.        ]])

In [27]:
pearsonr(_expr_sparse_csc[:,0],_expr_sparse_csc[:,10])

TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]

In [17]:
_expr_sparse.getcol(0)

<52899x1 sparse matrix of type '<class 'numpy.float64'>'
	with 305 stored elements in Compressed Sparse Row format>

In [18]:
_expr_sparse.getrow(0)

<1x12563 sparse matrix of type '<class 'numpy.float64'>'
	with 495 stored elements in Compressed Sparse Row format>

In [23]:
_expr_sparse_csr[:,0]

<52899x1 sparse matrix of type '<class 'numpy.float64'>'
	with 305 stored elements in Compressed Sparse Row format>

In [24]:
_expr_sparse_csr[0,:]

<1x12563 sparse matrix of type '<class 'numpy.float64'>'
	with 495 stored elements in Compressed Sparse Row format>